services:
  - type: web
    name: sales-app
    env: node
    region: singapore
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    plan: free
